# Generated by Django 6.0.4 on 2026-04-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountyCovidData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('geometry', models.TextField()),
                ('number_of_infections', models.IntegerField()),
            ],
        ),
    ]
