# Generated by Django 6.0.4 on 2026-04-30 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidIntVis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geometry', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CountyInfection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infections', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infection_data', to='CovidIntVis.county')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CountyCovidData',
        ),
        migrations.AddField(
            model_name='countyinfection',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='county_data', to='CovidIntVis.week'),
        ),
        migrations.AlterUniqueTogether(
            name='countyinfection',
            unique_together={('week', 'county')},
        ),
    ]
