# Generated by Django 6.0.4 on 2026-04-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CovidIntVis', '0002_county_countyinfection_week_delete_countycoviddata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='name',
            new_name='date',
        ),
    ]
