# Generated by Django 6.0.4 on 2026-04-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CovidIntVis', '0003_rename_name_week_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Week',
            new_name='WeeklyData',
        ),
        migrations.AlterUniqueTogether(
            name='county',
            unique_together={('name', 'geometry')},
        ),
    ]
