# Generated by Django 6.0.4 on 2026-04-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CovidIntVis', '0004_rename_week_weeklydata_alter_county_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countyinfection',
            old_name='week',
            new_name='weekly_data',
        ),
        migrations.AlterUniqueTogether(
            name='countyinfection',
            unique_together={('weekly_data', 'county')},
        ),
    ]
